[package]
name = "module-nft"
version = "1.0.0"
authors = ["Acala Developers"]
edition = "2018"

[dependencies]
serde = { version = "1.0.124", optional = true }
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false }
enumflags2 = { version = "0.6.3" }

frame-benchmarking = { version = "3.0", default-features = false, optional = true}
frame-support = { version = "3.0", default-features = false }
frame-system = { version = "3.0", default-features = false }
pallet-proxy = { version = "3.0", default-features = false }
primitives = { package = "edgeware-primitives", path = "../../node/primitives", default-features = false }
sp-runtime = { version = "3.0", default-features = false }
sp-std = { version = "3.0", default-features = false }

orml-nft = { path = "../orml-nft", default-features = false }
orml-traits = { package = "webb-traits", git = "https://github.com/webb-tools/anon", default-features = false }

[dev-dependencies]
sp-core = { version = "3.0", default-features = false }
sp-io = { version = "3.0", default-features = false }
pallet-balances = { version = "3.0", default-features = false }
pallet-utility = { version = "3.0", default-features = false }

orml-tokens = { package = "webb-tokens", git = "https://github.com/webb-tools/anon" }
currencies = { package = "webb-currencies", git = "https://github.com/webb-tools/anon" }

[features]
default = ["std"]
std = [
	"serde",
	"codec/std",
	"enumflags2/serde",
	"sp-std/std",
	"sp-runtime/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-proxy/std",
	"primitives/std",
	"orml-traits/std",
	"orml-nft/std",
	"enumflags2/serde",
]
runtime-benchmarks = [
	"frame-benchmarking",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
]
try-runtime = ["frame-support/try-runtime"]
